# Generated by Django 3.1 on 2020-08-11 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='latLong',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
