# Generated by Django 3.1 on 2020-08-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200811_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='administrative',
            new_name='administrative_area_level_1',
        ),
        migrations.RemoveField(
            model_name='address',
            name='property_name',
        ),
        migrations.RemoveField(
            model_name='address',
            name='state',
        ),
        migrations.AddField(
            model_name='address',
            name='administrative_area_level_2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='administrative_area_level_3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='administrative_area_level_4',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='administrative_area_level_5',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
