# Generated by Django 3.1 on 2020-08-13 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200813_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_description', models.CharField(max_length=3000, null=True)),
                ('country', models.CharField(max_length=100)),
                ('administrative_area_level_1', models.CharField(max_length=100, null=True)),
                ('administrative_area_level_2', models.CharField(max_length=100, null=True)),
                ('administrative_area_level_3', models.CharField(max_length=100, null=True)),
                ('administrative_area_level_4', models.CharField(max_length=100, null=True)),
                ('administrative_area_level_5', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100, null=True)),
                ('street_number', models.CharField(max_length=20, null=True)),
                ('zip_code', models.CharField(max_length=100, null=True)),
                ('full_address', models.CharField(max_length=250)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('latLong', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('propertyAddress', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.propertyaddress')),
            ],
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
