# Generated by Django 3.1 on 2020-08-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200813_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyaddress',
            name='autocomplete_address',
            field=models.CharField(default='none set', max_length=250),
            preserve_default=False,
        ),
    ]
