# Generated by Django 3.1 on 2020-08-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_address_latlong'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='administrative',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
